---
- name: Ensure that the application file permissions are set properly
  file: path={{ git_checkout_path }}
    recurse=yes
    owner={{ caddy_user }}
    group={{ caddy_group }}
    state=directory
