---

- name: install deadsnakes ppa
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: add NodeSource apt-key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add NodeSource repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_12.x bionic main"
    state: present

- name: add NodeSource source repository
  apt_repository:
    repo: "deb-src https://deb.nodesource.com/node_12.x bionic main"
    state: present

- name: add yarn apt-key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: add yarn repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present

- name: install base packages
  apt:
    state: present
    update_cache: yes
    force: no
    name:
      - vim
      - ntp
      - nmap
      - htop
      - tmux
      - git
      - openssl
      - libssl-dev
      - libffi-dev
      - software-properties-common
      - unattended-upgrades
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
      - python3.7
      - python3.7-dev
      - python3.7-venv
      - nodejs
      - yarn
      - make
      - ufw
      - goaccess
      - gcc
      - brotli
      - zopfli
  tags: packages

- name: remove cruft packages
  apt:
    state: absent
    name:
      - snapd

- name: set default policy
  ufw:
    state: enabled
    policy: reject
    direction: incoming

- name: ufw allow ssh
  ufw:
    rule: allow
    port: 22

- name: ufw allow nginx http
  ufw:
    rule: allow
    port: 80

- name: ufw allow nginx https
  ufw:
    rule: allow
    port: 443

- name: ufw reload
  ufw:
    state: reloaded
